In [1]:
import torch.nn as nn

In [2]:
import pandas as pandas

In [3]:
df = pandas.read_csv("/home/dan/Documents/idsAIDatasets/ddos_balanced/final_dataset.csv")

In [4]:
df

,Unnamed: 0,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,624,192.168.4.118-203.73.24.75-4504-80-6,192.168.4.118,4504,203.73.24.75,80,6,12/06/2010 08:34:32 AM,3974862,29,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
1,625,192.168.4.118-203.73.24.75-4504-80-6,192.168.4.118,4504,203.73.24.75,80,6,12/06/2010 08:34:36 AM,63,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
2,626,192.168.4.118-203.73.24.75-4505-80-6,192.168.4.118,4505,203.73.24.75,80,6,12/06/2010 08:34:36 AM,476078,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
3,627,192.168.4.118-203.73.24.75-4505-80-6,192.168.4.118,4505,203.73.24.75,80,6,12/06/2010 08:34:37 AM,151,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
4,628,192.168.4.118-203.73.24.75-4506-80-6,192.168.4.118,4506,203.73.24.75,80,6,12/06/2010 08:34:37 AM,472507,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12794622,1725894,172.31.67.50-209.85.203.113-53598-80-6,209.85.203.113,80,172.31.67.50,53598,6,20/02/2018 05:14:52,50,1,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
12794623,5681778,172.31.69.17-108.174.10.14-54599-443-6,172.31.69.17,54599,108.174.10.14,443,6,20/02/2018 03:08:35,306,3,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
12794624,6395326,172.31.0.2-172.31.65.49-53-61087-17,172.31.65.49,61087,172.31.0.2,53,17,20/02/2018 01:03:19,362,1,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
12794625,4926899,172.31.0.2-172.31.67.58-53-61580-17,172.31.67.58,61580,172.31.0.2,53,17,20/02/2018 12:43:11,303,1,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
12794626,7656685,169.254.169.254-172.31.65.89-80-49393-6,172.31.65.89,49393,169.254.169.254,80,6,20/02/2018 09:55:40,54,2,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [5]:
df1 = df[['Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Label']]

In [6]:
df1

,Src IP,Src Port,Dst IP,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Label
0,192.168.4.118,4504,203.73.24.75,80,6,3974862,29,ddos
1,192.168.4.118,4504,203.73.24.75,80,6,63,1,ddos
2,192.168.4.118,4505,203.73.24.75,80,6,476078,2,ddos
3,192.168.4.118,4505,203.73.24.75,80,6,151,2,ddos
4,192.168.4.118,4506,203.73.24.75,80,6,472507,2,ddos
...,...,...,...,...,...,...,...,...
12794622,209.85.203.113,80,172.31.67.50,53598,6,50,1,Benign
12794623,172.31.69.17,54599,108.174.10.14,443,6,306,3,Benign
12794624,172.31.65.49,61087,172.31.0.2,53,17,362,1,Benign
12794625,172.31.67.58,61580,172.31.0.2,53,17,303,1,Benign
12794626,172.31.65.89,49393,169.254.169.254,80,6,54,2,Benign